<?php
/**
 * ModalitiesIdStorePostRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Orthanc API
 *
 * This is the full documentation of the [REST API](https://book.orthanc-server.com/users/rest.html) of Orthanc.<p>This reference is automatically generated from the source code of Orthanc. A [shorter cheat sheet](https://book.orthanc-server.com/users/rest-cheatsheet.html) is part of the Orthanc Book.<p>An earlier, manually crafted version from August 2019, is [still available](2019-08-orthanc-openapi.html), but is not up-to-date anymore ([source](https://groups.google.com/g/orthanc-users/c/NUiJTEICSl8/m/xKeqMrbqAAAJ)).
 *
 * The version of the OpenAPI document: 1.11.3
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ModalitiesIdStorePostRequest Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ModalitiesIdStorePostRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = '_modalities__id__store_post_request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'asynchronous' => 'bool',
        'called_aet' => 'string',
        'host' => 'string',
        'local_aet' => 'string',
        'move_originator_aet' => 'string',
        'move_originator_id' => 'float',
        'permissive' => 'bool',
        'port' => 'float',
        'priority' => 'float',
        'resources' => 'string[]',
        'storage_commitment' => 'bool',
        'synchronous' => 'bool',
        'timeout' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'asynchronous' => null,
        'called_aet' => null,
        'host' => null,
        'local_aet' => null,
        'move_originator_aet' => null,
        'move_originator_id' => null,
        'permissive' => null,
        'port' => null,
        'priority' => null,
        'resources' => null,
        'storage_commitment' => null,
        'synchronous' => null,
        'timeout' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'asynchronous' => false,
		'called_aet' => false,
		'host' => false,
		'local_aet' => false,
		'move_originator_aet' => false,
		'move_originator_id' => false,
		'permissive' => false,
		'port' => false,
		'priority' => false,
		'resources' => false,
		'storage_commitment' => false,
		'synchronous' => false,
		'timeout' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'asynchronous' => 'Asynchronous',
        'called_aet' => 'CalledAet',
        'host' => 'Host',
        'local_aet' => 'LocalAet',
        'move_originator_aet' => 'MoveOriginatorAet',
        'move_originator_id' => 'MoveOriginatorID',
        'permissive' => 'Permissive',
        'port' => 'Port',
        'priority' => 'Priority',
        'resources' => 'Resources',
        'storage_commitment' => 'StorageCommitment',
        'synchronous' => 'Synchronous',
        'timeout' => 'Timeout'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'asynchronous' => 'setAsynchronous',
        'called_aet' => 'setCalledAet',
        'host' => 'setHost',
        'local_aet' => 'setLocalAet',
        'move_originator_aet' => 'setMoveOriginatorAet',
        'move_originator_id' => 'setMoveOriginatorId',
        'permissive' => 'setPermissive',
        'port' => 'setPort',
        'priority' => 'setPriority',
        'resources' => 'setResources',
        'storage_commitment' => 'setStorageCommitment',
        'synchronous' => 'setSynchronous',
        'timeout' => 'setTimeout'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'asynchronous' => 'getAsynchronous',
        'called_aet' => 'getCalledAet',
        'host' => 'getHost',
        'local_aet' => 'getLocalAet',
        'move_originator_aet' => 'getMoveOriginatorAet',
        'move_originator_id' => 'getMoveOriginatorId',
        'permissive' => 'getPermissive',
        'port' => 'getPort',
        'priority' => 'getPriority',
        'resources' => 'getResources',
        'storage_commitment' => 'getStorageCommitment',
        'synchronous' => 'getSynchronous',
        'timeout' => 'getTimeout'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('asynchronous', $data ?? [], null);
        $this->setIfExists('called_aet', $data ?? [], null);
        $this->setIfExists('host', $data ?? [], null);
        $this->setIfExists('local_aet', $data ?? [], null);
        $this->setIfExists('move_originator_aet', $data ?? [], null);
        $this->setIfExists('move_originator_id', $data ?? [], null);
        $this->setIfExists('permissive', $data ?? [], null);
        $this->setIfExists('port', $data ?? [], null);
        $this->setIfExists('priority', $data ?? [], null);
        $this->setIfExists('resources', $data ?? [], null);
        $this->setIfExists('storage_commitment', $data ?? [], null);
        $this->setIfExists('synchronous', $data ?? [], null);
        $this->setIfExists('timeout', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets asynchronous
     *
     * @return bool|null
     */
    public function getAsynchronous()
    {
        return $this->container['asynchronous'];
    }

    /**
     * Sets asynchronous
     *
     * @param bool|null $asynchronous If `true`, run the job in asynchronous mode, which means that the REST API call will immediately return, reporting the identifier of a job. Prefer this flavor wherever possible.
     *
     * @return self
     */
    public function setAsynchronous($asynchronous)
    {
        if (is_null($asynchronous)) {
            throw new \InvalidArgumentException('non-nullable asynchronous cannot be null');
        }
        $this->container['asynchronous'] = $asynchronous;

        return $this;
    }

    /**
     * Gets called_aet
     *
     * @return string|null
     */
    public function getCalledAet()
    {
        return $this->container['called_aet'];
    }

    /**
     * Sets called_aet
     *
     * @param string|null $called_aet Called AET that is used for this commands, defaults to `AET` configuration option. Allows you to overwrite the destination AET for a specific operation.
     *
     * @return self
     */
    public function setCalledAet($called_aet)
    {
        if (is_null($called_aet)) {
            throw new \InvalidArgumentException('non-nullable called_aet cannot be null');
        }
        $this->container['called_aet'] = $called_aet;

        return $this;
    }

    /**
     * Gets host
     *
     * @return string|null
     */
    public function getHost()
    {
        return $this->container['host'];
    }

    /**
     * Sets host
     *
     * @param string|null $host Host that is used for this commands, defaults to `Host` configuration option. Allows you to overwrite the destination host for a specific operation.
     *
     * @return self
     */
    public function setHost($host)
    {
        if (is_null($host)) {
            throw new \InvalidArgumentException('non-nullable host cannot be null');
        }
        $this->container['host'] = $host;

        return $this;
    }

    /**
     * Gets local_aet
     *
     * @return string|null
     */
    public function getLocalAet()
    {
        return $this->container['local_aet'];
    }

    /**
     * Sets local_aet
     *
     * @param string|null $local_aet Local AET that is used for this commands, defaults to `DicomAet` configuration option. Ignored if `DicomModalities` already sets `LocalAet` for this modality.
     *
     * @return self
     */
    public function setLocalAet($local_aet)
    {
        if (is_null($local_aet)) {
            throw new \InvalidArgumentException('non-nullable local_aet cannot be null');
        }
        $this->container['local_aet'] = $local_aet;

        return $this;
    }

    /**
     * Gets move_originator_aet
     *
     * @return string|null
     */
    public function getMoveOriginatorAet()
    {
        return $this->container['move_originator_aet'];
    }

    /**
     * Sets move_originator_aet
     *
     * @param string|null $move_originator_aet Move originator AET that is used for this commands, in order to fake a C-MOVE SCU
     *
     * @return self
     */
    public function setMoveOriginatorAet($move_originator_aet)
    {
        if (is_null($move_originator_aet)) {
            throw new \InvalidArgumentException('non-nullable move_originator_aet cannot be null');
        }
        $this->container['move_originator_aet'] = $move_originator_aet;

        return $this;
    }

    /**
     * Gets move_originator_id
     *
     * @return float|null
     */
    public function getMoveOriginatorId()
    {
        return $this->container['move_originator_id'];
    }

    /**
     * Sets move_originator_id
     *
     * @param float|null $move_originator_id Move originator ID that is used for this commands, in order to fake a C-MOVE SCU
     *
     * @return self
     */
    public function setMoveOriginatorId($move_originator_id)
    {
        if (is_null($move_originator_id)) {
            throw new \InvalidArgumentException('non-nullable move_originator_id cannot be null');
        }
        $this->container['move_originator_id'] = $move_originator_id;

        return $this;
    }

    /**
     * Gets permissive
     *
     * @return bool|null
     */
    public function getPermissive()
    {
        return $this->container['permissive'];
    }

    /**
     * Sets permissive
     *
     * @param bool|null $permissive If `true`, ignore errors during the individual steps of the job.
     *
     * @return self
     */
    public function setPermissive($permissive)
    {
        if (is_null($permissive)) {
            throw new \InvalidArgumentException('non-nullable permissive cannot be null');
        }
        $this->container['permissive'] = $permissive;

        return $this;
    }

    /**
     * Gets port
     *
     * @return float|null
     */
    public function getPort()
    {
        return $this->container['port'];
    }

    /**
     * Sets port
     *
     * @param float|null $port Port that is used for this commands, defaults to `Port` configuration option. Allows you to overwrite the destination port for a specific operation.
     *
     * @return self
     */
    public function setPort($port)
    {
        if (is_null($port)) {
            throw new \InvalidArgumentException('non-nullable port cannot be null');
        }
        $this->container['port'] = $port;

        return $this;
    }

    /**
     * Gets priority
     *
     * @return float|null
     */
    public function getPriority()
    {
        return $this->container['priority'];
    }

    /**
     * Sets priority
     *
     * @param float|null $priority In asynchronous mode, the priority of the job. The lower the value, the higher the priority.
     *
     * @return self
     */
    public function setPriority($priority)
    {
        if (is_null($priority)) {
            throw new \InvalidArgumentException('non-nullable priority cannot be null');
        }
        $this->container['priority'] = $priority;

        return $this;
    }

    /**
     * Gets resources
     *
     * @return string[]|null
     */
    public function getResources()
    {
        return $this->container['resources'];
    }

    /**
     * Sets resources
     *
     * @param string[]|null $resources List of the Orthanc identifiers of all the DICOM resources to be sent
     *
     * @return self
     */
    public function setResources($resources)
    {
        if (is_null($resources)) {
            throw new \InvalidArgumentException('non-nullable resources cannot be null');
        }
        $this->container['resources'] = $resources;

        return $this;
    }

    /**
     * Gets storage_commitment
     *
     * @return bool|null
     */
    public function getStorageCommitment()
    {
        return $this->container['storage_commitment'];
    }

    /**
     * Sets storage_commitment
     *
     * @param bool|null $storage_commitment Whether to chain C-STORE with DICOM storage commitment to validate the success of the transmission: https://book.orthanc-server.com/users/storage-commitment.html#chaining-c-store-with-storage-commitment
     *
     * @return self
     */
    public function setStorageCommitment($storage_commitment)
    {
        if (is_null($storage_commitment)) {
            throw new \InvalidArgumentException('non-nullable storage_commitment cannot be null');
        }
        $this->container['storage_commitment'] = $storage_commitment;

        return $this;
    }

    /**
     * Gets synchronous
     *
     * @return bool|null
     */
    public function getSynchronous()
    {
        return $this->container['synchronous'];
    }

    /**
     * Sets synchronous
     *
     * @param bool|null $synchronous If `true`, run the job in synchronous mode, which means that the HTTP answer will directly contain the result of the job. This is the default, easy behavior, but it is *not* desirable for long jobs, as it might lead to network timeouts.
     *
     * @return self
     */
    public function setSynchronous($synchronous)
    {
        if (is_null($synchronous)) {
            throw new \InvalidArgumentException('non-nullable synchronous cannot be null');
        }
        $this->container['synchronous'] = $synchronous;

        return $this;
    }

    /**
     * Gets timeout
     *
     * @return float|null
     */
    public function getTimeout()
    {
        return $this->container['timeout'];
    }

    /**
     * Sets timeout
     *
     * @param float|null $timeout Timeout for the C-STORE command, in seconds
     *
     * @return self
     */
    public function setTimeout($timeout)
    {
        if (is_null($timeout)) {
            throw new \InvalidArgumentException('non-nullable timeout cannot be null');
        }
        $this->container['timeout'] = $timeout;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


